### ISSUE TITLE
New Users aren't automatically entered into the SEconomy Journal 

### ISSUE THREAD

**Issue by Skilz-Discipile** [Quinci135/SEconomy#1]
Tested on TShock 1.4.0.5 Pre-12 and TShock 1.4.1.2 Pre-15 - The SEconomy plugin works perfectly, except for creating a bank account for users when they join. All existing accounts work and function perfectly normal, as with the entire plugin, just registering doesn't work and therefore new users cannot experience the plugin and all dependent features. 

https://gyazo.com/e5afaa226d0d85ea5c171d4441b94597
Logging in and out (and logging in and out of existing accounts) causes this error (There is no error in the console window + debug enabled). 

I really hope this is a fixable bug, and If it can be fixed, I will be of as much service as I can be.

**Comment by Quinci135** [comment]
The "There was an error processing your request" means your character failed to login to an account properly. Must be something on your end (maybe: a plugin, remember-position issues, ssc issues) that's causing tshock login to fail. I didn't encounter this issue myself when updating the plugin and testing it out nor have I changed how accounts work or how they are created. I didn't have any pre-existing databases either. Kojiro (a server owner) hasn't noted any issues with the plugin so far, and I was indeed able to create and use an seconomy account on there.
*Have you tried with a fresh setup of seconomy?

**Comment by Skilz-Discipile** [comment]
Hello once again - I've resolved the issue, you were correct, a certain plugin was causing the login error which made SEconomy unable to create an account! Thank you so much for the assistance! :D
